services:
  vllm-llama3_2-direct:
    build:
      context: .
      dockerfile: Dockerfile
    image: vllm-llama3_2-direct:local
    container_name: vllm-llama3_2-direct
    ports:
      - "30200:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_VISIBLE_DEVICES=0
      - MAX_MODEL_LEN=512
      - VLLM_FLASH_ATTN_VERSION=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ipc: host
    restart: unless-stopped